// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Donation struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
	GoalID int64       `json:"goal_id"`
	// must be positive
	Amount      int64     `json:"amount"`
	IsAnonymous bool      `json:"is_anonymous"`
	CreatedAt   time.Time `json:"created_at"`
}

type Event struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Place string `json:"place"`
	// event date and time
	Date      time.Time `json:"date"`
	CreatedAt time.Time `json:"created_at"`
}

// tracks which users have booked which events
type EventBooking struct {
	ID       int64     `json:"id"`
	UserID   int64     `json:"user_id"`
	EventID  int64     `json:"event_id"`
	BookedAt time.Time `json:"booked_at"`
}

type Goal struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	// in smallest currency unit, e.g., cents
	TargetAmount    pgtype.Int8 `json:"target_amount"`
	CollectedAmount int64       `json:"collected_amount"`
	IsActive        bool        `json:"is_active"`
	CreatedAt       time.Time   `json:"created_at"`
}

type User struct {
	ID             int64       `json:"id"`
	Email          string      `json:"email"`
	Name           pgtype.Text `json:"name"`
	Balance        int64       `json:"balance"`
	HashedPassword pgtype.Text `json:"hashed_password"`
	CreatedAt      time.Time   `json:"created_at"`
}
