// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	BookEvent(ctx context.Context, arg BookEventParams) (EventBooking, error)
	CancelEventBooking(ctx context.Context, arg CancelEventBookingParams) error
	CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEvent(ctx context.Context, id int64) error
	DeleteGoal(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetEventBooking(ctx context.Context, arg GetEventBookingParams) (EventBooking, error)
	GetGoal(ctx context.Context, id int64) (Goal, error)
	GetGoalForUpdate(ctx context.Context, id int64) (Goal, error)
	GetUser(ctx context.Context, id int64) (User, error)
	IsEventBooked(ctx context.Context, arg IsEventBookedParams) (bool, error)
	ListEventBookings(ctx context.Context, eventID int64) ([]ListEventBookingsRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error)
	ListUpcomingEvents(ctx context.Context, arg ListUpcomingEventsParams) ([]Event, error)
	ListUserBookings(ctx context.Context, userID int64) ([]ListUserBookingsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateGoalCollectedAmount(ctx context.Context, arg UpdateGoalCollectedAmountParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (User, error)
}

var _ Querier = (*Queries)(nil)
