// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGoal(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetGoal(ctx context.Context, id int64) (Goal, error)
	GetGoalForUpdate(ctx context.Context, id int64) (Goal, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateGoalCollectedAmount(ctx context.Context, arg UpdateGoalCollectedAmountParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) (User, error)
}

var _ Querier = (*Queries)(nil)
